fix rotsec and shole

diff --git a/roles/terminal/files/.local/bin/shole b/roles/terminal/files/.local/bin/shole
--- a/roles/terminal/files/.local/bin/shole
+++ b/roles/terminal/files/.local/bin/shole
@@ -1,17 +1,18 @@
 #!/usr/bin/env bash
-
 shole() {
     local bin_name=""
     local flag_help=0
     local flag_shell="sh"
-
+    local flag_path="$HOME/.local/bin"
+    
     # Function to display help
     help() {
-        echo "shole: show the contents of a file"
-        echo "usage: shole [-h] [-s shell] path"
-        echo "  -h, --help  show this help message and exit"
-        echo "  -s, --shell shell, shell to use e.g. fish, sh. Default is sh"
-        echo "  path, path to the shell script"
+        echo "shole: create a new executable script with a shebang"
+        echo "usage: shole [-h] [-s shell] [-p path] name"
+        echo "  -h, --help        show this help message and exit"
+        echo "  -s, --shell       shell/language to use: sh, bash, py, python, zig. Default is sh"
+        echo "  -p, --path        directory to place the script. Default is ~/.local/bin"
+        echo "  name              name of the script to create"
         return 0
     }
     
@@ -28,6 +29,14 @@ shole() {
                     return 1
                 fi
                 flag_shell="$2"
+                shift 2
+                ;;
+            -p|--path)
+                if [[ -z "$2" ]]; then
+                    echo "shole: error: -p/--path requires an argument" >&2
+                    return 1
+                fi
+                flag_path="$2"
                 shift 2
                 ;;
             -*)
@@ -49,12 +58,10 @@ shole() {
     
     # Check if file path was provided
     if [[ -z "$bin_name" ]]; then
-        echo "shole: error: the following arguments are required: path"
+        echo "shole: error: the following arguments are required: name"
         return 1
     fi
-
-
-    local bin_path=~/.local/bin/$bin_name
+    local bin_path="$flag_path/$bin_name"
     
     # Set shell string based on flag
     local shell_str
@@ -68,22 +75,17 @@ shole() {
         zig)
             shell_str='//usr/bin/env zig run "$0" -- "$@"; exit "$?"'
             ;;
-        js|node)
-            shell_str="#!/usr/bin/env node"
-            ;;
-        go)
-            shell_str='//usr/bin/env go run "$0" "$@"; exit "$?"'
-            ;;
         *)
-            shell_str="/usr/bin/env bash"
+            shell_str="#!/usr/bin/env bash"
             ;;
     esac
     
+    # Create directory if it doesn't exist
+    mkdir -p "$flag_path"
+    
     # Create the file with shebang
-    echo "${shell_str}" > $bin_path
-
+    echo "${shell_str}" > "$bin_path"
     # Make the file executable
-    chmod +x $bin_path
+    chmod +x "$bin_path"
 }
-
 shole "$@"
